version: '3.9'

services:
  app:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "app/main.py"]
