services:
  app:
    build: .
    container_name: myapp
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: ["sh", "-c", "alembic upgrade head && python app/main.py"]
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:latest
    container_name: mydb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
