"""Add video_url to videos

Revision ID: 0f8881cd869b
Revises:
Create Date: 2024-07-25 01:33:28.500846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0f8881cd869b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('channel_name', sa.String(), nullable=True))
    op.alter_column('videos', 'views',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_videos_channel_id', table_name='videos')
    op.drop_column('videos', 'channel_id')
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_videos_channel_id', 'videos', ['channel_id'], unique=False)
    op.alter_column('videos', 'views',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('videos', 'channel_name')
    op.drop_column('videos', 'video_url')
    # ### end Alembic commands ###
