"""Add unique constraint to video_url

Revision ID: 5f565738e3c4
Revises: 0f8881cd869b
Create Date: 2024-07-26 01:36:49.033998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5f565738e3c4"
down_revision: Union[str, None] = "0f8881cd869b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_video_url", "videos", ["video_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_video_url", "videos", type_="unique")
    # ### end Alembic commands ###
