"""Add User and Video models2

Revision ID: 84a6db597a95
Revises: 9b12cef5ada2
Create Date: 2024-07-26 03:23:34.174036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84a6db597a95"
down_revision: Union[str, None] = "9b12cef5ada2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("users"):
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
        op.create_index(
            op.f("ix_users_telegram_user_id"),
            "users",
            ["telegram_user_id"],
            unique=True,
        )

    if not table_exists("videos"):
        op.create_table(
            "videos",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("description", sa.Text(), nullable=False),
            sa.Column("views", sa.Integer(), nullable=False),
            sa.Column("video_url", sa.String(), nullable=False),
            sa.Column("channel_name", sa.String(), nullable=False),
            sa.Column(
                "user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("video_url", name="uq_video_url"),
        )
        op.create_index(op.f("ix_videos_id"), "videos", ["id"], unique=False)
        op.create_index(op.f("ix_videos_title"), "videos", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists("videos"):
        op.drop_index(op.f("ix_videos_title"), table_name="videos")
        op.drop_index(op.f("ix_videos_id"), table_name="videos")
        op.drop_table("videos")

    if table_exists("users"):
        op.drop_index(op.f("ix_users_telegram_user_id"), table_name="users")
        op.drop_index(op.f("ix_users_id"), table_name="users")
        op.drop_table("users")
    # ### end Alembic commands ###
