"""Create users and videos tables

Revision ID: 9b12cef5ada2
Revises: 5f565738e3c4
Create Date: 2024-07-26 02:16:47.515902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9b12cef5ada2"
down_revision: Union[str, None] = "5f565738e3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_telegram_user_id"), "users", ["telegram_user_id"], unique=True
    )

    op.add_column("videos", sa.Column("user_id", sa.Integer(), nullable=True))

    op.alter_column("videos", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "videos",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column("videos", "views", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("videos", "video_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "videos", "channel_name", existing_type=sa.VARCHAR(), nullable=False
    )

    op.execute("INSERT INTO users (telegram_user_id) VALUES (0)")

    op.execute(
        "UPDATE videos SET user_id = (SELECT id FROM users WHERE telegram_user_id = 0) WHERE user_id IS NULL"
    )

    op.alter_column("videos", "user_id", existing_type=sa.Integer(), nullable=False)

    op.create_foreign_key(None, "videos", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.alter_column("videos", "channel_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("videos", "video_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("videos", "views", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "videos",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column("videos", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("videos", "user_id")

    op.drop_index(op.f("ix_users_telegram_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
